# Generated by Django 2.2.6 on 2019-10-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=48, unique=True)),
                ('address_street_name', models.CharField(max_length=50, unique=True)),
                ('suburb', models.CharField(max_length=40, unique=True)),
                ('postcode', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
                ('contact_name', models.CharField(max_length=48)),
                ('email_address', models.CharField(max_length=62, unique=True)),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
