# Generated by Django 2.2.6 on 2019-10-08 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191008_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=48, unique=True, validators=[django.core.validators.RegexValidator('^\\d{a,z}$')]),
        ),
    ]
