# Generated by Django 2.2.6 on 2019-10-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191008_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_name',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
