# Generated by Django 2.2.6 on 2019-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20191008_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email_address',
            field=models.EmailField(max_length=62),
        ),
    ]
