# Generated by Django 2.2.6 on 2019-10-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20191008_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='suburb',
            field=models.CharField(max_length=40),
        ),
    ]
